apiVersion: templates.gatekeeper.sh/v1alpha1
kind: ConstraintTemplate
metadata:
  name:  blockednamespace
  labels:
    app: namespace-whitelisting
spec:
  crd:
    spec:
      names:
        kind: BlockedNamespace
  targets:      
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sconstraints.example
        
        violation[{"msg": msg}] {
            input.request.object.kind == "Namespace"
            namespace_name = input.request.object.metadata.name
            whitelist := input.parameters.name
            not whitelist[namespace_name]
            msg := sprintf("Namespace %v is not in the whitelist of allowed namespaces", [namespace_name])
        }
      
