apiVersion: batch/v1
kind: Job
metadata:
  name: label-constraint-template-job
spec:
  template:
    spec:
      containers:
      - name: label-constraint-template
        image: openshift4/ose-cli:latest
        command:
        - bash
        - "-c"
        - |
          # Get the cluster name
          CLUSTER_NAME=$(oc config current-context)
          
          # Label the constraint template with the cluster name 
          oc label constrainttemplate BlockedNamespace cluster-name=$CLUSTER_NAME
          # (O) using oc patch as well
      restartPolicy: Never
